"""Optional demo target for the Kernel File I/O cookbook.

This is a single-file Modal app that serves a tiny "parking receipt lookup"
website matching the selectors `main.py` automates out of the box:

- `input#email` and `input#order_number` on the lookup form
- `button#generateBtn` submits the form
- `a.btn-download` on the confirmation page serves a PDF receipt with a
  `Content-Disposition: attachment` header, which triggers a real browser
  download that the cookbook captures via CDP

Deploy it to your own Modal workspace with one command:

    modal deploy demo_site.py

Then point the cookbook at the printed URL:

    WEBSITE_URL=https://<workspace>--file-io-demo-site-web.modal.run uv run main.py

The app scales to zero when idle, so it costs nothing at rest. It has no
state, no dependencies beyond FastAPI, and generates the PDF in pure Python.
"""

from datetime import datetime, timezone

import modal

app = modal.App("file-io-demo-site")

image = modal.Image.debian_slim(python_version="3.12").pip_install(
    "fastapi[standard]"
)

# Shared styles keep the two pages visually consistent.
_STYLE = """
  :root { color-scheme: light; }
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body {
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
    background: linear-gradient(160deg, #0f172a 0%, #1e293b 100%);
    min-height: 100vh;
    display: flex;
    align-items: center;
    justify-content: center;
    padding: 24px;
    color: #0f172a;
  }
  .card {
    background: #ffffff;
    border-radius: 16px;
    box-shadow: 0 24px 48px rgba(0, 0, 0, 0.35);
    max-width: 440px;
    width: 100%;
    padding: 40px;
  }
  .badge {
    display: inline-block;
    font-size: 12px;
    font-weight: 600;
    letter-spacing: 0.08em;
    text-transform: uppercase;
    color: #0369a1;
    background: #e0f2fe;
    border-radius: 999px;
    padding: 4px 12px;
    margin-bottom: 16px;
  }
  h1 { font-size: 24px; margin-bottom: 8px; }
  p.sub { color: #64748b; font-size: 14px; margin-bottom: 24px; line-height: 1.5; }
  label { display: block; font-size: 13px; font-weight: 600; margin-bottom: 6px; }
  input {
    width: 100%;
    font-size: 15px;
    padding: 10px 12px;
    border: 1px solid #cbd5e1;
    border-radius: 8px;
    margin-bottom: 16px;
  }
  input:focus { outline: 2px solid #0ea5e9; border-color: #0ea5e9; }
  button, .btn-download {
    display: block;
    width: 100%;
    text-align: center;
    text-decoration: none;
    font-size: 15px;
    font-weight: 600;
    color: #ffffff;
    background: #0284c7;
    border: none;
    border-radius: 8px;
    padding: 12px;
    cursor: pointer;
  }
  button:hover, .btn-download:hover { background: #0369a1; }
  dl { margin: 24px 0; border-top: 1px solid #e2e8f0; }
  dl > div {
    display: flex;
    justify-content: space-between;
    gap: 16px;
    padding: 10px 0;
    border-bottom: 1px solid #e2e8f0;
    font-size: 14px;
  }
  dt { color: #64748b; }
  dd { font-weight: 600; text-align: right; word-break: break-all; }
"""


def _page(body: str) -> str:
    return f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Acme Parking Receipts</title>
  <style>{_STYLE}</style>
</head>
<body>
  <div class="card">{body}</div>
</body>
</html>"""


def _pdf_escape(text: str) -> str:
    return text.replace("\\", r"\\").replace("(", r"\(").replace(")", r"\)")


def _build_receipt_pdf(email: str, order_number: str) -> bytes:
    """Build a small one-page PDF receipt in pure Python (no dependencies)."""
    issued = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    lines = [
        ("Acme Parking - Official Receipt", 20),
        ("", 12),
        (f"Order number: {order_number}", 12),
        (f"Email: {email}", 12),
        (f"Issued: {issued}", 12),
        ("", 12),
        ("Location: Lot 42, 100 Demo Way", 12),
        ("Duration: 2 hours 15 minutes", 12),
        ("Amount paid: $12.50", 12),
        ("", 12),
        ("Generated by the Kernel File I/O cookbook demo site.", 10),
    ]

    parts = ["BT", "/F1 12 Tf", "1 0 0 1 72 720 Tm", "16 TL"]
    for text, size in lines:
        parts.append(f"/F1 {size} Tf")
        parts.append(f"({_pdf_escape(text)}) Tj")
        parts.append("T*")
    parts.append("ET")
    content = "\n".join(parts).encode("latin-1", "replace")

    objects = [
        b"<< /Type /Catalog /Pages 2 0 R >>",
        b"<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
        b"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] "
        b"/Resources << /Font << /F1 5 0 R >> >> /Contents 4 0 R >>",
        b"<< /Length %d >>\nstream\n%s\nendstream" % (len(content), content),
        b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
    ]

    out = bytearray(b"%PDF-1.4\n")
    offsets = []
    for i, obj in enumerate(objects, start=1):
        offsets.append(len(out))
        out += b"%d 0 obj\n%s\nendobj\n" % (i, obj)

    xref_pos = len(out)
    out += b"xref\n0 %d\n" % (len(objects) + 1)
    out += b"0000000000 65535 f \n"
    for offset in offsets:
        out += b"%010d 00000 n \n" % offset
    out += (
        b"trailer\n<< /Size %d /Root 1 0 R >>\nstartxref\n%d\n%%%%EOF\n"
        % (len(objects) + 1, xref_pos)
    )
    return bytes(out)


# min_containers=0 (the default) means the app scales to zero when idle and
# costs nothing at rest. scaledown_window keeps a warm container briefly so
# multi-step automation runs stay snappy.
@app.function(image=image, min_containers=0, scaledown_window=120)
@modal.asgi_app()
def web():
    from fastapi import FastAPI
    from fastapi.responses import HTMLResponse, Response

    api = FastAPI(title="Kernel File I/O demo site")

    @api.get("/", response_class=HTMLResponse)
    def lookup_form() -> str:
        return _page(
            """
            <span class="badge">Demo target</span>
            <h1>Parking receipt lookup</h1>
            <p class="sub">Enter the email and order number from your booking
            to retrieve your receipt.</p>
            <form action="/receipt" method="get">
              <label for="email">Email address</label>
              <input id="email" name="email" type="email" required
                     placeholder="you@example.com">
              <label for="order_number">Parking reference</label>
              <input id="order_number" name="order_number" type="text" required
                     placeholder="110011001">
              <button id="generateBtn" type="submit">Look Up Parking</button>
            </form>
            """
        )

    @api.get("/receipt", response_class=HTMLResponse)
    def receipt_page(email: str = "", order_number: str = "") -> str:
        from html import escape
        from urllib.parse import urlencode

        query = urlencode({"email": email, "order_number": order_number})
        return _page(
            f"""
            <span class="badge">Order found</span>
            <h1>Receipt ready</h1>
            <p class="sub">We found a parking session matching your details.
            Download the PDF receipt below.</p>
            <dl>
              <div><dt>Order number</dt><dd>{escape(order_number)}</dd></div>
              <div><dt>Email</dt><dd>{escape(email)}</dd></div>
              <div><dt>Amount paid</dt><dd>$12.50</dd></div>
            </dl>
            <a class="btn-download" href="/receipt.pdf?{query}">
              Download receipt (PDF)
            </a>
            """
        )

    @api.get("/receipt.pdf")
    def receipt_pdf(email: str = "", order_number: str = "") -> Response:
        safe_order = "".join(
            ch for ch in order_number if ch.isalnum() or ch in "-_"
        ) or "receipt"
        pdf = _build_receipt_pdf(email, order_number)
        return Response(
            content=pdf,
            media_type="application/pdf",
            headers={
                # The attachment disposition is what makes the browser treat
                # this as a download, which the cookbook captures via CDP.
                "Content-Disposition": (
                    f'attachment; filename="parking-receipt-{safe_order}.pdf"'
                )
            },
        )

    return api
